spring.application.name=msvc_gateway_server
#Eureka Server
server.port=8090
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG