resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 40s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 4s
        slow-call-rate-threshold: 50
    instances:
      reports:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 6s
    instances:
      reports:
        base-config: defecto
