spring.application.name=msvc-oauth
# Eureka Server Configuration
server.port=9000
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG