spring.application.name=msvc-punto-venta
# Port configuration
config.base-url.endpoint.msvc-registro-ventas=http://msvc-registro-ventas
config.base-url.endpoint.msvc-clientes=http://msvc-clientes
config.base-url.endpoint.msvc-inventario=http://msvc-inventario
# Eureka Server Configuration
server.port=${PORT:0}
eureka.instance.instance-id=${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka